### ISSUE TITLE
Re: AGS10 i2c how to read

### ISSUE THREAD

**Issue by letshin** [gaveshalabs/AGS10_sensor#1]
Hi, I was hoping that you could explain how the i2c addresses are read from the AGS10 please.

I'm looking at the  datasheet - how do I read the VOC data?

Do I just read 5 bytes from 0x00 and the voc is bytes 2, 3, and 4 in ppb?

**Comment by lihini** [comment]
If you're using this python library, then you don't have to worry about reading specific bytes. Just pass the relevant I2C instance into the sensor. Following code reads the ppb from the sensor.

```
from ags10 import AGS10
from machine import I2C

# Init
sensor = AGS10(I2C(0, freq=10000))

# Enable CRC check for measurements
sensor.check_crc = True

# Measure TVOC in parts per billion (ppb)
tvoc = sensor.total_volatile_organic_compounds_ppb
```

**Comment by letshin** [comment]
I was using it to bit-bang a sensor read but have sorted this now. Thanks!
